name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Bundling YAML
      run: |
        npm install
        npm run build
    - name: Create a gh-pages branch
      run: git checkout --orphan gh-pages
    - uses: EndBug/add-and-commit@v6
      with:
        author_name: nakorndev
        author_email: nakorndev@gmail.com
        branch: gh-pages
        add: docs --force
        message: Deploy to GitHub Pages
        push: origin gh-pages --force
        token: ${{ secrets.GITHUB_TOKEN }}
